# Generated by Django 4.0.1 on 2023-04-04 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinValueValidator(3)])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MinValueValidator(3)])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator(6)])),
                ('email', models.EmailField(max_length=40, validators=[django.core.validators.MinValueValidator(8)])),
                ('address', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(10)])),
            ],
        ),
    ]
