# Generated by Django 4.0.1 on 2023-04-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_description'),
        ('Order', '0002_order_products_alter_order_address_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='Products.Products'),
        ),
    ]
