# Generated by Django 4.0.1 on 2023-04-06 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(to='Products.Size'),
        ),
    ]
